spring:
  application:
    name: server

  rsocket:
    server:
      transport: tcp
      port: 7000

  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql