# Matrosov Danil IKBO-01-21
services:
  app1: &app-template
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/filestore
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  app2:
    <<: *app-template

  app3:
    <<: *app-template

  app4:
    <<: *app-template

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
      - app4

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=filestore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: