
CREATE TABLE task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMP,
    completed   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);